fixing mantis 898
git-svn-id: https://gnunet.org/svn/GNUnet@1846 140774ce-b5e7-0310-ab8b-a85725594a96

diff --git a/contrib/autoinstall b/contrib/autoinstall
--- a/contrib/autoinstall
+++ b/contrib/autoinstall
@@ -2,45 +2,47 @@
 echo "This script compiles, installs and starts GNUnet."
 echo "It must be run as root (sorry)."
 echo "GNUnet will be installed to /usr/local/."
-echo "Configuration files are created in /etc/gnunet.conf"
-echo "and for all users in their home directories"
-echo "(in /home/*/.gnunet/)."
+echo "Configuration files are created in /etc/gnunetd.conf."
+echo "Users still have to run gnunet-setup to create their"
+echo "personal configuration file ($USER/gnunet.conf)."
 echo "An init-script will be placed under /etc/init.d/gnunetd"
 echo " "
-touch /etc/gnunet.conf || echo "Not root.  Aborting."
-touch /etc/gnunet.conf || exit -1
-if test -f contrib/gnunet.root
+if test $USER != root
+then 
+  echo "Not root.  Aborting."
+  exit -1
+fi
+if test -f contrib/initgnunet
 then
  echo "Please press CTRL-C now to abort or RETURN to continue."
  read
 else
- echo "This script must be run from the GNUnet-VERSION/ directory."
+ echo "This script must be run from the GNUnet/ source directory."
  exit -1
 fi
 cp contrib/initgnunet /etc/init.d/gnunetd
 chmod +x /etc/init.d/gnunetd
-cp contrib/gnunet.root /etc/gnunet.conf 
-for n in /home/*
-do
- mkdir -p $n/.gnunet/
- cp contrib/gnunet.user $n/.gnunet/gnunet.conf
- chown -R `echo $n | sed -e "s/\/home\///"` $n/.gnunet/
-done
 ./configure --prefix=/usr/local
 make -s
 make -s install
-export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
-export PATH=/usr/local/bin:$PATH
-gnunetd
-gnunet-gtk &
+echo " "
+echo "Press RETURN to start the interactive setup tool."
+read
+/usr/local/bin/gnunet-setup -d || exit -1
+echo " "
 echo "Note that you can start GNUnet text-user interfaces"
 echo "with the commands "
 echo " "
-echo "# $HOME/bin/gnunet-search"
-echo "# $HOME/bin/gnunet-download"
-echo "# $HOME/bin/gnunet-insert"
+echo "$ /usr/local/bin/gnunet-search"
+echo "$ /usr/local/bin/gnunet-download"
+echo "$ /usr/local/bin/gnunet-insert"
 echo " "
-echo "You will have to edit your startup sequence to"
+echo "You may want to edit your startup sequence to"
 echo "automatically start gnunetd whenever your system boots."
 echo " "
-echo "Visit http://www.ovmj.org/GNUnet/ for further information."
+echo "Visit http://gnunet.org/ for further information."
+echo " "
+echo "Press RETURN to run gnunet-update and then start gnunetd."
+read
+/usr/local/bin/gnunet-update
+/usr/local/bin/gnunetd
